// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Signup(arg1:backend.SignUpPayload):Promise<void>;
