// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetUserByID(arg1:string):Promise<backend.UserResponse>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:backend.LoginPayload):Promise<backend.LoginResponse>;

export function Signup(arg1:backend.SignUpPayload):Promise<backend.UserResponse>;
